spring.application.name=equilibria

spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/equilibria}
spring.datasource.username=postgres
spring.datasource.password=12345678
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

app.jwt.secret=${JWT_SECRET:Y2FtYmlhLWVzdGUtc2VjcmV0by1lbi1wcm9kdWNjaW9uLW1pbi0zMi1ieXRlcw==}
app.jwt.expiration-ms=86400000

app.encryption.secret=${ENCRYPTION_SECRET:3q6t9w$C&F)J@NcRfUjXn2r5u8x/A?Dz}

app.rate-limit.capacity=500
app.rate-limit.refill-minutes=1

gemini.api-key=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

app.storage.type=${STORAGE_TYPE:local}
app.storage.local-path=${STORAGE_LOCAL_PATH:/data/uploads}

app.cors.allowed-origins=${FRONTEND_URL:http://localhost:5173},http://localhost:3000

server.port=8080
server.servlet.context-path=/api

app.push.enabled=${PUSH_ENABLED:false}

# ↓ Configura esto con tu Gmail y tu contraseña de aplicación
mail.enabled=true
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=equilibria6738@gmail.com
spring.mail.password=lxhztjfgsajpjdqp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui
springdoc.swagger-ui.enabled=true

logging.level.pe.upc.equilibria=INFO
logging.level.org.springframework.security=WARN
